// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://errzltarqbkkcldzivud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycnpsdGFycWJra2NsZHppdnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjU4NjcsImV4cCI6MjA2NTQwMTg2N30.DZgsXC3Gj3V0ASwma769Q118ZOD5cy2uu3E21umCX88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);